[package]
name = "simding_benches"
version = "0.1.0"
authors = ["Clement Marescaux <marcle15@student.westerdals.no>"]

[dependencies]
rayon = "*"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "simd_benches"
harness = false